name: Build and deploy nuget package
 
on: 
  push:
    branches:
      - master
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: | 
            4.6.2
            4.8.1
            6.0.x
            8.0.x

      - name: Restore NuGet Packages
        run: dotnet restore /p:Platform="Any CPU"

      - name: Build
        run: dotnet build --configuration Release /p:Platform="Any CPU"

      - name: Pack
        run: dotnet pack --configuration Release /p:Platform="Any CPU"

      - name: Publish
        run: dotnet nuget push LibSquishNet\bin\Release\*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --key ${{ secrets.NUGET_API_KEY }}